### ISSUE TITLE
Add component example

### ISSUE THREAD

**Issue by daerogami** [daerogami/NunjucksStarterProject#3]
Under templates, there should be a components folder. Example 'component' should be an *.njk file containing a macro called 'insert' and that macro should be invoked on the index page. Ideally this insert macro takes a model param which fills out copy such as header/body text to said component.

**Comment by zachary-cauchi** [comment]
Hi @daerogami. I'd be happy to take it in if you'd like.

**Comment by daerogami** [comment]
@Zach128 By all means. Thanks!

**Comment by zachary-cauchi** [comment]
Just finished writing up the example. Could you help me push it so you can review it and suggest improvements?

**Comment by daerogami** [comment]
Certainly, let me know what assistance I can provide.

I saw you fork'd the repo for your change; is it allowing you to create a PR against this repo?

**Comment by zachary-cauchi** [comment]
My mistake; I hadn't realised I was trying to push to the base repository. Pull request available [here](https://github.com/daerogami/NunjucksStarterProject/pull/5).
